name: Deploy Vite + Vue 3 to GitHub Pages

on:
  # Trigger workflow on pushes to the main branch
  push:
    branches:
      - main

  # Allows manual triggering of the workflow
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust the Node.js version if necessary

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Ensure your build script is defined in package.json

      - name: Deploy to GitHub Pages
        run: |
          # Configure Git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Switch to gh-pages branch
          git fetch origin
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
          
          # Copy built files to root (dist is the Vite output directory)
          rm -rf *
          cp -r ../dist/* .
          
          # Commit and push changes to gh-pages branch
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
