name: Deploy Vite + Vue 3 to GitHub Pages

on:
  # Run this workflow when pushing to the main branch
  push:
    branches:
      - main

  # Allows manual triggering of the workflow
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the Node.js version that suits your project

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Ensure your build script is defined in package.json

      - name: Deploy to GitHub Pages
        run: |
          # Configure git user details
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Initialize gh-pages branch
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin
          git worktree add gh-pages
          cp -r dist/* gh-pages/

          # Commit and push to gh-pages branch
          cd gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
